const products=[
 {id:1,name:"Pebble ceramic vase",category:"home",tag:"Bestseller",price:28,rating:4.9,reviews:128,img:"https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=700&q=80",description:"A softly sculpted vase with a hand-finished feel. Beautiful with blooms or all on its own."},
 {id:2,name:"Weekend canvas tote",category:"style",tag:"New",price:34,rating:4.8,reviews:96,img:"https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=700&q=80",description:"Your new everyday carryall. Roomy, sturdy and made for market mornings and weekend wanderings."},
 {id:3,name:"Cloud knit throw",category:"home",tag:"Cozy pick",price:49,rating:4.9,reviews:214,img:"https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=700&q=80",description:"A wonderfully soft knit blanket for slow mornings, movie nights and everything in between."},
 {id:4,name:"Mini mushroom lamp",category:"tech",tag:"Design darling",price:39,rating:4.7,reviews:74,img:"https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=80",description:"A tiny, touch-controlled glow that makes any corner feel warmer. USB-C rechargeable."},
 {id:5,name:"Daily ritual mug",category:"home",tag:"Staff favorite",price:22,rating:4.8,reviews:181,img:"https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=700&q=80",description:"The just-right mug for your morning ritual. Smooth stoneware, generous handle, happy color."},
 {id:6,name:"Sunlit reading glasses",category:"style",tag:"Easy on the eyes",price:26,rating:4.6,reviews:52,img:"https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=700&q=80",description:"Lightweight frames with a warm tint and a flattering shape for long, lovely reading sessions."},
 {id:7,name:"Botanical hand balm",category:"beauty",tag:"Small luxury",price:18,rating:4.9,reviews:203,img:"https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=700&q=80",description:"A rich but never-greasy balm made with shea butter and botanical oils. Keep one everywhere."},
 {id:8,name:"Pocket sound speaker",category:"tech",tag:"Good vibes",price:45,rating:4.8,reviews:89,img:"https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=700&q=80",description:"Small enough for your tote, big enough to fill a room with your favorite soundtrack."}
];
let filter="all",cart=JSON.parse(localStorage.getItem("shopday-cart")||"[]"),modalProduct=null,modalQty=1;
const $=s=>document.querySelector(s);
function stars(r){return `<span class="stars">★★★★★</span><span>${r}</span>`}
function renderProducts(){let q=$("#search-input").value.toLowerCase(),list=products.filter(p=>(filter==="all"||p.category===filter)&&(`${p.name} ${p.tag}`.toLowerCase().includes(q)));let sort=$("#sort-select").value;if(sort==="price-low")list.sort((a,b)=>a.price-b.price);if(sort==="price-high")list.sort((a,b)=>b.price-a.price);if(sort==="rating")list.sort((a,b)=>b.rating-a.rating);$("#result-count").textContent=`${list.length} ${list.length===1?"find":"finds"}`;$("#product-grid").innerHTML=list.map(p=>`<article class="product-card" data-id="${p.id}"><div class="product-image"><img src="${p.img}" alt="${p.name}" loading="lazy"><span class="product-tag">${p.tag}</span><button class="wishlist" aria-label="Save ${p.name}">♡</button></div><div class="product-info"><h3>${p.name}</h3><div class="rating">${stars(p.rating)}</div><div class="product-bottom"><div class="price">$${p.price.toFixed(2)}</div><button class="add-button" data-add="${p.id}" aria-label="Add ${p.name}">+</button></div></div></article>`).join("");$("#empty-state").hidden=!!list.length}
function save(){localStorage.setItem("shopday-cart",JSON.stringify(cart))}
function cartTotal(){return cart.reduce((s,x)=>s+x.price*x.qty,0)}
function renderCart(){let count=cart.reduce((s,x)=>s+x.qty,0);$("#cart-count").textContent=count;$("#drawer-count").textContent=`(${count})`;$("#cart-items").innerHTML=cart.map(x=>`<div class="cart-line"><img src="${x.img}" alt=""><div class="cart-line-info"><strong>${x.name}</strong><small>$${x.price.toFixed(2)}</small><div class="line-controls"><div class="mini-quantity"><button data-change="${x.id}" data-amount="-1">−</button><span>${x.qty}</span><button data-change="${x.id}" data-amount="1">+</button></div><span class="line-price">$${(x.price*x.qty).toFixed(2)}</span></div></div></div>`).join("");$("#cart-empty").classList.toggle("show",!cart.length);$("#cart-summary").style.display=cart.length?"block":"none";$("#cart-subtotal").textContent=`$${cartTotal().toFixed(2)}`;save()}
function add(id,qty=1){let p=products.find(x=>x.id===id),line=cart.find(x=>x.id===id);if(line)line.qty+=qty;else cart.push({...p,qty});renderCart();showToast(`${p.name} added to cart`)}
function showToast(t){$("#toast-text").textContent=t;$("#toast").classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$("#toast").classList.remove("show"),2300)}
function openCart(){ $("#overlay").classList.add("open");$("#cart-drawer").classList.add("open")}
function closeCart(){ $("#overlay").classList.remove("open");$("#cart-drawer").classList.remove("open")}
function openModal(p){modalProduct=p;modalQty=1;$("#modal-img").src=p.img;$("#modal-img").alt=p.name;$("#modal-tag").textContent=p.tag;$("#modal-name").textContent=p.name;$("#modal-rating").innerHTML=stars(`${p.rating} · ${p.reviews} reviews`);$("#modal-description").textContent=p.description;$("#modal-price").textContent=`$${p.price.toFixed(2)}`;$("#modal-qty").textContent=1;$("#product-modal").classList.add("open")}
function closeModal(){$("#product-modal").classList.remove("open")}
document.addEventListener("click",e=>{let cat=e.target.closest("[data-filter]");if(cat){filter=cat.dataset.filter;document.querySelectorAll(".category-card").forEach(x=>x.classList.toggle("active",x.dataset.filter===filter));renderProducts();$("#products").scrollIntoView({behavior:"smooth",block:"start"})}let addButton=e.target.closest("[data-add]");if(addButton){e.stopPropagation();add(+addButton.dataset.add)}let wishlist=e.target.closest(".wishlist");if(wishlist){e.stopPropagation();wishlist.textContent=wishlist.textContent==="♡"?"♥":"♡";wishlist.style.color=wishlist.textContent==="♥"?"#e88569":""}let card=e.target.closest(".product-card");if(card&&!e.target.closest("button"))openModal(products.find(p=>p.id===+card.dataset.id));let change=e.target.closest("[data-change]");if(change){let line=cart.find(x=>x.id===+change.dataset.change);line.qty+=+change.dataset.amount;if(line.qty<1)cart=cart.filter(x=>x.id!==line.id);renderCart()}});
$("#search-form").addEventListener("submit",e=>{e.preventDefault();renderProducts();$("#products").scrollIntoView({behavior:"smooth"})});$("#search-input").addEventListener("input",renderProducts);$("#search-category").addEventListener("change",e=>{filter=e.target.value;document.querySelectorAll(".category-card").forEach(x=>x.classList.toggle("active",x.dataset.filter===filter));renderProducts()});$("#sort-select").addEventListener("change",renderProducts);
$("#cart-open").onclick=openCart;$("#cart-close").onclick=closeCart;$("#overlay").onclick=closeCart;$("#browse-button").onclick=closeCart;$("#modal-close").onclick=closeModal;$("#product-modal").addEventListener("click",e=>{if(e.target.id==="product-modal")closeModal()});document.querySelectorAll("[data-modal-qty]").forEach(b=>b.onclick=()=>{modalQty=Math.max(1,modalQty+ +b.dataset.modalQty);$("#modal-qty").textContent=modalQty});$("#modal-add").onclick=()=>{add(modalProduct.id,modalQty);closeModal();openCart()};$("#checkout-button").onclick=()=>showToast("Checkout is ready for your next step ✦");document.querySelector(".mobile-menu").onclick=()=>document.querySelector(".nav-bar").classList.toggle("mobile-open");
renderProducts();renderCart();
